### ISSUE TITLE
Eula issue

### ISSUE THREAD

**Issue by saschaarthur** [NativeScript/nativescript-cloud#163] opened 2019-04-01 21:06 UTC
Hello,

I have an issue regarding nativescript eula using nativescript-cloud 1.17.1

Running following command (in a bitbucket pipeline using this docker container: https://cloud.docker.com/repository/docker/scratchy/nativescript-cli/ using tag 5.3.0-28.0.3-1.17.1):

> 
> docker run -e TNS_USER=cloud_user -e TNS_PASS=cloud_pass -it scratchy/nativescript-cli:5.3.0-28.0.3-1.17.1 sh -c "echo start && \\
> mkdir -p /test && \\
> \cd /test && \\
> git clone https://github.com/NativeScript/nativescript-app-templates.git && \\
> tns create my-hello-world-js --template nativescript-app-templates/packages/template-hello-world && \\
> cd my-hello-world-js && \\
> tns accept eula && \\
> tns dev-login \\${TNS_USER} \\${TNS_PASS} && \\
> tns cloud build android --bundle --clean --accountId=1"

Getting following output:
```
...
Accepting EULA located at https://www.nativescript.org/nativescript-sidekick/eula.

EULA has been accepted.
Progress Software collects and uses your personal data (first name, last name and email address) to:
• Allow cloud build usage according to your NativeScript Sidekick subscription plan.
You can review the Progress Software Privacy Policy at https://www.progress.com/legal/privacy-policy
You can submit a GDPR Data Subject Access Request at https://app.onetrust.com/app/#/webform/7897e80a-b8a4-4797-883a-bdacfe1ab8e4
EULA is not accepted, cannot use cloud services.

```
This looks like a bug for me. Either the Eula is accepted (like said in the output) or its not. But at least the state should be the same for tns cloud build & tns accept eula ...

Maybe issues because its termless?

Edit: dont know where it breaks yet (on which version).. will try to figure it out...

at least tag 5.1.1-28.0.3-1.15.2 is working..

**Comment by rosen-vladimirov** [comment] 2019-04-01 22:54
Hey @saschaarthur ,
Thanks for reporting this issue. We've found the cause of the issue and we are preparing a fix. As a workaround you can call `tns accept eula && tns accept eula` (second execution should be correct).

**Comment by saschaarthur** [comment] 2019-04-01 23:13
thanks a lot will verify within the next 24h

**Comment by saschaarthur** [comment] 2019-04-02 06:31
tns accept && tns accept && ... works.
thanks for this, can you point me to the release where its fixed if its done?

**Comment by rosen-vladimirov** [comment] 2019-04-02 09:09
Hey @saschaarthur ,
We've just released a new version of `nativescript-cloud` - `1.17.2`. The issue should be resolved in it.

**Closed** 2019-04-02 09:10 UTC
Labels: bug
